-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\whdlAWGNGenerator\logImplementation.vhd
-- Created: 2026-03-04 09:56:05
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: logImplementation
-- Source Path: whdlAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/logImplementation
-- Hierarchy Level: 2
-- Model version: 2.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.AWGNGenerator_pkg.ALL;

ENTITY logImplementation IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u0_48_48                          :   IN    std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
        e                                 :   OUT   std_logic_vector(30 DOWNTO 0)  -- ufix31_En24
        );
END logImplementation;


ARCHITECTURE rtl OF logImplementation IS

  -- Component Declarations
  COMPONENT log
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u0_48_48                        :   IN    std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
          e                               :   OUT   std_logic_vector(30 DOWNTO 0)  -- ufix31_En24
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : log
    USE ENTITY work.log(rtl);

  -- Signals
  SIGNAL u0_48_48_unsigned                : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL Delay_reg                        : vector_of_unsigned48(0 TO 15);  -- ufix48 [16]
  SIGNAL Delay_out1                       : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- ufix16_En9
  SIGNAL Constant_out1_dtc                : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL y                                : std_logic_vector(30 DOWNTO 0);  -- ufix31
  SIGNAL y_unsigned                       : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL Switch_out1                      : unsigned(30 DOWNTO 0);  -- ufix31_En24

BEGIN
  u_log : log
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              u0_48_48 => u0_48_48,  -- ufix48_En48
              e => y  -- ufix31_En24
              );

  u0_48_48_unsigned <= unsigned(u0_48_48);

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_reg <= (OTHERS => to_unsigned(0, 48));
      ELSIF enb = '1' THEN
        Delay_reg(0) <= u0_48_48_unsigned;
        Delay_reg(1 TO 15) <= Delay_reg(0 TO 14);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(15);

  Constant_out1 <= to_unsigned(16#0000#, 16);

  Constant_out1_dtc <= Constant_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  y_unsigned <= unsigned(y);

  
  Switch_out1 <= Constant_out1_dtc WHEN Delay_out1 = to_unsigned(0, 48) ELSE
      y_unsigned;

  e <= std_logic_vector(Switch_out1);

END rtl;

