-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\whdlAWGNGenerator\AWGNGenerator.vhd
-- Created: 2026-03-04 09:56:05
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-06
-- Target subsystem base rate: 1e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- awgn_re                       ce_out        1e-06
-- awgn_im                       ce_out        1e-06
-- valid                         ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: AWGNGenerator
-- Source Path: whdlAWGNGenerator/AWGNGenerator
-- Hierarchy Level: 0
-- Model version: 2.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.AWGNGenerator_pkg.ALL;

ENTITY AWGNGenerator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        snrdB                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En9
        ce_out                            :   OUT   std_logic;
        awgn_re                           :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En16
        awgn_im                           :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En16
        valid                             :   OUT   std_logic
        );
END AWGNGenerator;


ARCHITECTURE rtl OF AWGNGenerator IS

  -- Component Declarations
  COMPONENT dBtoLinearConverter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          snrdB                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En9
          noiseVar                        :   OUT   std_logic_vector(21 DOWNTO 0)  -- ufix22_En18
          );
  END COMPONENT;

  COMPONENT GaussianNoiseWithUnitVar
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          x0                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          x1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  COMPONENT GaussianNoiseWithReqVar
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          noiseVar                        :   IN    std_logic_vector(21 DOWNTO 0);  -- ufix22_En18
          x0                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          x1                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          awgn_re                         :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En16
          awgn_im                         :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dBtoLinearConverter
    USE ENTITY work.dBtoLinearConverter(rtl);

  FOR ALL : GaussianNoiseWithUnitVar
    USE ENTITY work.GaussianNoiseWithUnitVar(rtl);

  FOR ALL : GaussianNoiseWithReqVar
    USE ENTITY work.GaussianNoiseWithReqVar(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL dBtoLinearConverter_out1         : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL dBtoLinearConverter_out1_unsigned : unsigned(21 DOWNTO 0);  -- ufix22_En18
  SIGNAL Delay_reg                        : vector_of_unsigned22(0 TO 29);  -- ufix22 [30]
  SIGNAL Delay_out1                       : unsigned(21 DOWNTO 0);  -- ufix22_En18
  SIGNAL GaussianNoiseWithUnitVar_out1    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL GaussianNoiseWithUnitVar_out2    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL GaussianNoiseWithReqVar_out1_re  : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL GaussianNoiseWithReqVar_out1_im  : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL GaussianNoiseWithReqVar_out2     : std_logic;

BEGIN
  u_dBtoLinearConverter : dBtoLinearConverter
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              snrdB => snrdB,  -- sfix16_En9
              noiseVar => dBtoLinearConverter_out1  -- ufix22_En18
              );

  u_GaussianNoiseWithUnitVar : GaussianNoiseWithUnitVar
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              x0 => GaussianNoiseWithUnitVar_out1,  -- sfix16_En11
              x1 => GaussianNoiseWithUnitVar_out2  -- sfix16_En11
              );

  u_GaussianNoiseWithReqVar : GaussianNoiseWithReqVar
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              noiseVar => std_logic_vector(Delay_out1),  -- ufix22_En18
              x0 => GaussianNoiseWithUnitVar_out1,  -- sfix16_En11
              x1 => GaussianNoiseWithUnitVar_out2,  -- sfix16_En11
              awgn_re => GaussianNoiseWithReqVar_out1_re,  -- sfix26_En16
              awgn_im => GaussianNoiseWithReqVar_out1_im,  -- sfix26_En16
              validOut => GaussianNoiseWithReqVar_out2
              );

  dBtoLinearConverter_out1_unsigned <= unsigned(dBtoLinearConverter_out1);

  enb <= clk_enable;

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_reg <= (OTHERS => to_unsigned(16#000000#, 22));
      ELSIF enb = '1' THEN
        Delay_reg(0) <= dBtoLinearConverter_out1_unsigned;
        Delay_reg(1 TO 29) <= Delay_reg(0 TO 28);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(29);

  ce_out <= clk_enable;

  awgn_re <= GaussianNoiseWithReqVar_out1_re;

  awgn_im <= GaussianNoiseWithReqVar_out1_im;

  valid <= GaussianNoiseWithReqVar_out2;

END rtl;

