# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/DAT096/DAT096-krish/Embedded-System-Project-DAT096-krishna/Board_2/Board_2/Board_2.srcs/sources_1/bd/design_2/ip/design_2_top_awgn_0_0/design_2_top_awgn_0_0.xci
# IP: The module: 'design_2_top_awgn_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/DAT096/DAT096-krish/Embedded-System-Project-DAT096-krishna/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_top_awgn_0_0/src/Eclypse-Z7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_top_awgn_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: Z:/DAT096/DAT096-krish/Embedded-System-Project-DAT096-krishna/Board_2/Board_2/Board_2.srcs/sources_1/bd/design_2/ip/design_2_top_awgn_0_0/design_2_top_awgn_0_0.xci
# IP: The module: 'design_2_top_awgn_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/DAT096/DAT096-krish/Embedded-System-Project-DAT096-krishna/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_top_awgn_0_0/src/Eclypse-Z7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_top_awgn_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
