-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\whdlAWGNGenerator\GaussianNoiseWithReqVar.vhd
-- Created: 2026-03-04 09:56:05
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: GaussianNoiseWithReqVar
-- Source Path: whdlAWGNGenerator/AWGNGenerator/GaussianNoiseWithReqVar
-- Hierarchy Level: 1
-- Model version: 2.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.AWGNGenerator_pkg.ALL;

ENTITY GaussianNoiseWithReqVar IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        noiseVar                          :   IN    std_logic_vector(21 DOWNTO 0);  -- ufix22_En18
        x0                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        x1                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        awgn_re                           :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En16
        awgn_im                           :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En16
        validOut                          :   OUT   std_logic
        );
END GaussianNoiseWithReqVar;


ARCHITECTURE rtl OF GaussianNoiseWithReqVar IS

  -- Signals
  SIGNAL x0_signed                        : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL x1_signed                        : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Gain_out1_re                     : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Gain_out1_im                     : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Add1_cast                        : signed(16 DOWNTO 0);  -- sfix17_En11
  SIGNAL Add1_out1_re                     : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Add1_out1_im                     : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Delay5_reg_re                    : vector_of_signed16(0 TO 1);  -- sfix16_En11 [2]
  SIGNAL Delay5_reg_im                    : vector_of_signed16(0 TO 1);  -- sfix16_En11 [2]
  SIGNAL Delay5_out1_re                   : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Delay5_out1_im                   : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL noiseVar_unsigned                : unsigned(21 DOWNTO 0);  -- ufix22_En18
  SIGNAL Delay4_reg                       : vector_of_unsigned22(0 TO 1);  -- ufix22 [2]
  SIGNAL Delay4_out1                      : unsigned(21 DOWNTO 0);  -- ufix22_En18
  SIGNAL Product1_cast                    : signed(22 DOWNTO 0);  -- sfix23_En18
  SIGNAL Product1_mul_temp                : signed(38 DOWNTO 0);  -- sfix39_En29
  SIGNAL Product1_Re                      : signed(37 DOWNTO 0);  -- sfix38_En29
  SIGNAL Product11_cast                   : signed(22 DOWNTO 0);  -- sfix23_En18
  SIGNAL Product11_mul_temp               : signed(38 DOWNTO 0);  -- sfix39_En29
  SIGNAL Product1_Im                      : signed(37 DOWNTO 0);  -- sfix38_En29
  SIGNAL Delay6_out1_re                   : signed(37 DOWNTO 0);  -- sfix38_En29
  SIGNAL Delay6_out1_im                   : signed(37 DOWNTO 0);  -- sfix38_En29
  SIGNAL Data_Type_Conversion_out1_re     : signed(25 DOWNTO 0);  -- sfix26_En16
  SIGNAL Data_Type_Conversion_out1_im     : signed(25 DOWNTO 0);  -- sfix26_En16
  SIGNAL Constant1_out1                   : std_logic;
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL Delay2_reg                       : std_logic_vector(9 DOWNTO 0);  -- ufix1 [10]
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Delay1_reg                       : std_logic_vector(15 DOWNTO 0);  -- ufix1 [16]
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL Delay3_reg                       : std_logic_vector(6 DOWNTO 0);  -- ufix1 [7]
  SIGNAL Delay3_out1                      : std_logic;
  SIGNAL Delay8_reg                       : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL Delay8_out1                      : std_logic;

BEGIN
  x0_signed <= signed(x0);

  x1_signed <= signed(x1);

  Gain_out1_re <= to_signed(16#0000#, 16);
  Gain_out1_im <= x1_signed;

  Add1_out1_re <= x0_signed + Gain_out1_re;
  Add1_cast <= resize(Gain_out1_im, 17);
  Add1_out1_im <= Add1_cast(15 DOWNTO 0);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_reg_re <= (OTHERS => to_signed(16#0000#, 16));
        Delay5_reg_im <= (OTHERS => to_signed(16#0000#, 16));
      ELSIF enb = '1' THEN
        Delay5_reg_im(0) <= Add1_out1_im;
        Delay5_reg_im(1) <= Delay5_reg_im(0);
        Delay5_reg_re(0) <= Add1_out1_re;
        Delay5_reg_re(1) <= Delay5_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay5_process;

  Delay5_out1_re <= Delay5_reg_re(1);
  Delay5_out1_im <= Delay5_reg_im(1);

  noiseVar_unsigned <= unsigned(noiseVar);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_reg <= (OTHERS => to_unsigned(16#000000#, 22));
      ELSIF enb = '1' THEN
        Delay4_reg(0) <= noiseVar_unsigned;
        Delay4_reg(1) <= Delay4_reg(0);
      END IF;
    END IF;
  END PROCESS Delay4_process;

  Delay4_out1 <= Delay4_reg(1);

  Product1_cast <= signed(resize(Delay4_out1, 23));
  Product1_mul_temp <= Delay5_out1_re * Product1_cast;
  Product1_Re <= Product1_mul_temp(37 DOWNTO 0);

  Product11_cast <= signed(resize(Delay4_out1, 23));
  Product11_mul_temp <= Delay5_out1_im * Product11_cast;
  Product1_Im <= Product11_mul_temp(37 DOWNTO 0);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_out1_re <= to_signed(0, 38);
        Delay6_out1_im <= to_signed(0, 38);
      ELSIF enb = '1' THEN
        Delay6_out1_re <= Product1_Re;
        Delay6_out1_im <= Product1_Im;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Data_Type_Conversion_out1_re <= resize(Delay6_out1_re(37 DOWNTO 13), 26);
  Data_Type_Conversion_out1_im <= resize(Delay6_out1_im(37 DOWNTO 13), 26);

  awgn_re <= std_logic_vector(Data_Type_Conversion_out1_re);

  awgn_im <= std_logic_vector(Data_Type_Conversion_out1_im);

  Constant1_out1 <= '1';

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay_out1 <= Constant1_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay2_reg(0) <= Delay_out1;
        Delay2_reg(9 DOWNTO 1) <= Delay2_reg(8 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1 <= Delay2_reg(9);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay1_reg(0) <= Delay2_out1;
        Delay1_reg(15 DOWNTO 1) <= Delay1_reg(14 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(15);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay3_reg(0) <= Delay1_out1;
        Delay3_reg(6 DOWNTO 1) <= Delay3_reg(5 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay3_process;

  Delay3_out1 <= Delay3_reg(6);

  Delay8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay8_reg(0) <= Delay3_out1;
        Delay8_reg(2 DOWNTO 1) <= Delay8_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay8_process;

  Delay8_out1 <= Delay8_reg(2);

  validOut <= Delay8_out1;

END rtl;

