# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.srcs/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/design_2_ZmodScopeController_0_2.xci
# IP: The module: 'design_2_ZmodScopeController_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/src/ZmodADC_SynchonizationFIFO/ZmodADC_SynchonizationFIFO.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZmodADC_SynchonizationFIFO || ORIG_REF_NAME==ZmodADC_SynchonizationFIFO} -quiet] -quiet

# XDC: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/src/ZmodADC_SynchonizationFIFO/ZmodADC_SynchonizationFIFO.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZmodADC_SynchonizationFIFO || ORIG_REF_NAME==ZmodADC_SynchonizationFIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/src/ZmodADC_SynchonizationFIFO/ZmodADC_SynchonizationFIFO_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZmodADC_SynchonizationFIFO || ORIG_REF_NAME==ZmodADC_SynchonizationFIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/ConstrsZmodADC.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ZmodScopeController_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/src/ConstrZmodADC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ZmodScopeController_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.srcs/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/design_2_ZmodScopeController_0_2.xci
# IP: The module: 'design_2_ZmodScopeController_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/src/ZmodADC_SynchonizationFIFO/ZmodADC_SynchonizationFIFO.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZmodADC_SynchonizationFIFO || ORIG_REF_NAME==ZmodADC_SynchonizationFIFO} -quiet] -quiet

# XDC: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/src/ZmodADC_SynchonizationFIFO/ZmodADC_SynchonizationFIFO.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZmodADC_SynchonizationFIFO || ORIG_REF_NAME==ZmodADC_SynchonizationFIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/src/ZmodADC_SynchonizationFIFO/ZmodADC_SynchonizationFIFO_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZmodADC_SynchonizationFIFO || ORIG_REF_NAME==ZmodADC_SynchonizationFIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/ConstrsZmodADC.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ZmodScopeController_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/devandla/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodScopeController_0_2/src/ConstrZmodADC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ZmodScopeController_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
