# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Eclypse Z7.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ZmodAWGController_0_0/design_1_ZmodAWGController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ZmodAWGController_0_0 || ORIG_REF_NAME==design_1_ZmodAWGController_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_prbs_axis_master_32_0_0/design_1_prbs_axis_master_32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_prbs_axis_master_32_0_0 || ORIG_REF_NAME==design_1_prbs_axis_master_32_0_0} -quiet] -quiet

# XDC: z:/DAT096/signal generator/project_2/project_2.gen/sources_1/bd/design_1/design_1_ooc.xdc
