# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/arikb/Desktop/Eclypse-Z7-Master.xdc

# Block Designs: bd/vcsel_block_design/vcsel_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vcsel_block_design || ORIG_REF_NAME==vcsel_block_design} -quiet] -quiet

# IP: bd/vcsel_block_design/ip/vcsel_block_design_vcsel_demo_top_0_0/vcsel_block_design_vcsel_demo_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vcsel_block_design_vcsel_demo_top_0_0 || ORIG_REF_NAME==vcsel_block_design_vcsel_demo_top_0_0} -quiet] -quiet

# IP: bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vcsel_block_design_clk_wiz_0_0 || ORIG_REF_NAME==vcsel_block_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/vcsel_block_design/ip/vcsel_block_design_ila_0_0/vcsel_block_design_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vcsel_block_design_ila_0_0 || ORIG_REF_NAME==vcsel_block_design_ila_0_0} -quiet] -quiet

# XDC: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.gen/sources_1/bd/vcsel_block_design/vcsel_block_design_ooc.xdc
