set_property SRC_FILE_INFO {cfile:C:/Users/qianzha/Desktop/Embedded-System-Project-DAT096/Board_2/Board_2/Board_2.srcs/constrs_1/new/Board_2.xdc rfile:../../../Board_2.srcs/constrs_1/new/Board_2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D18 IOSTANDARD LVCMOS33 } [get_ports { sys_clk }]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N19 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { adc_dco_p }]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N20 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { adc_dco_n }]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M19 IOSTANDARD LVDS_25 } [get_ports { ZmodAdcClkIn_p_0 }]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M20 IOSTANDARD LVDS_25 } [get_ports { ZmodAdcClkIn_n_0 }]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T16 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[0]  }]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T17 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[1]  }]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R19 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[2]  }]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T19 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[3]  }]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R18 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[4]  }]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T18 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[5]  }]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P17 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[6]  }]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P18 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[7]  }]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P16 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[8]  }]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R16 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[9]  }]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N15 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[10] }]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P15 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[11] }]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J18 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[12] }]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K18 IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports { dZmodADC_Data_0[13] }]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L19 IOSTANDARD LVCMOS25 } [get_ports { sZmodADC_CS_0   }]   ;# S[16]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K19 IOSTANDARD LVCMOS25 } [get_ports { sZmodADC_Sclk_0 }]   ;# S[19]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L18 IOSTANDARD LVCMOS25 } [get_ports { sZmodADC_SDIO_0 }]   ;# S[18] inout
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K20 IOSTANDARD LVCMOS25 } [get_ports { iZmodSync_0     }]   ;# S[17]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L22 IOSTANDARD LVCMOS25 } [get_ports { sZmodCh1CouplingH_0 }] ;# S[20]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J22 IOSTANDARD LVCMOS25 } [get_ports { sZmodCh1CouplingL_0 }] ;# S[21]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L21 IOSTANDARD LVCMOS25 } [get_ports { sZmodCh2CouplingH_0 }] ;# S[22]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J21 IOSTANDARD LVCMOS25 } [get_ports { sZmodCh2CouplingL_0 }] ;# S[23]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N22 IOSTANDARD LVCMOS25 } [get_ports { sZmodCh1GainH_0 }]     ;# S[24]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P22 IOSTANDARD LVCMOS25 } [get_ports { sZmodCh1GainL_0 }]     ;# S[25]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M21 IOSTANDARD LVCMOS25 } [get_ports { sZmodCh2GainH_0 }]     ;# S[26]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M22 IOSTANDARD LVCMOS25 } [get_ports { sZmodCh2GainL_0 }]     ;# S[27]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J20 IOSTANDARD LVCMOS25 } [get_ports { sZmodRelayComH_0 }]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K21 IOSTANDARD LVCMOS25 } [get_ports { sZmodRelayComL_0 }]
