-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\whdlAWGNGenerator\TausUniformRandGen.vhd
-- Created: 2026-03-04 09:56:05
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TausUniformRandGen
-- Source Path: whdlAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/TausUniformRandGen
-- Hierarchy Level: 2
-- Model version: 2.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY TausUniformRandGen IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u0_16_16                          :   OUT   std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
        u1_16_16                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16_En16
        );
END TausUniformRandGen;


ARCHITECTURE rtl OF TausUniformRandGen IS

  -- Component Declarations
  COMPONENT TausURNG1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          a                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT TausURNG2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          b                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  COMPONENT ConcatandExtract
    PORT( a                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          b                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          u0_48_48                        :   OUT   std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
          u1_16_16                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16_En16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : TausURNG1
    USE ENTITY work.TausURNG1(rtl);

  FOR ALL : TausURNG2
    USE ENTITY work.TausURNG2(rtl);

  FOR ALL : ConcatandExtract
    USE ENTITY work.ConcatandExtract(rtl);

  -- Signals
  SIGNAL a_32_0                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL b_32_0                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL u0_48_48                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL u1_16_16_tmp                     : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_TausURNG1 : TausURNG1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              a => a_32_0  -- uint32
              );

  u_TausURNG2 : TausURNG2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              b => b_32_0  -- uint32
              );

  u_ConcatandExtract : ConcatandExtract
    PORT MAP( a => a_32_0,  -- uint32
              b => b_32_0,  -- uint32
              u0_48_48 => u0_48_48,  -- ufix48_En48
              u1_16_16 => u1_16_16_tmp  -- ufix16_En16
              );

  u0_16_16 <= u0_48_48;

  u1_16_16 <= u1_16_16_tmp;

END rtl;

