-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\whdlAWGNGenerator\RangeReconstruction_block.vhd
-- Created: 2026-03-04 09:56:05
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RangeReconstruction_block
-- Source Path: whdlAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/logImplementation/log/RangeReconstruction
-- Hierarchy Level: 4
-- Model version: 2.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.AWGNGenerator_pkg.ALL;

ENTITY RangeReconstruction_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        y_e                               :   IN    std_logic_vector(30 DOWNTO 0);  -- sfix31_En27
        exp_e                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        e                                 :   OUT   std_logic_vector(30 DOWNTO 0)  -- ufix31_En24
        );
END RangeReconstruction_block;


ARCHITECTURE rtl OF RangeReconstruction_block IS

  -- Signals
  SIGNAL exp_e_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay_reg                        : vector_of_unsigned8(0 TO 1);  -- ufix8 [2]
  SIGNAL Delay_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant_out1                    : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL Product_cast                     : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Product_mul_temp                 : signed(41 DOWNTO 0);  -- sfix42_En32
  SIGNAL Product_out1                     : signed(40 DOWNTO 0);  -- sfix41_En32
  SIGNAL Product_out1_1                   : signed(34 DOWNTO 0);  -- sfix35_En28
  SIGNAL Delay2_out1                      : signed(34 DOWNTO 0);  -- sfix35_En28
  SIGNAL y_e_signed                       : signed(30 DOWNTO 0);  -- sfix31_En27
  SIGNAL Delay1_reg                       : vector_of_signed31(0 TO 1);  -- sfix31 [2]
  SIGNAL Delay1_out1                      : signed(30 DOWNTO 0);  -- sfix31_En27
  SIGNAL Delay3_out1                      : signed(30 DOWNTO 0);  -- sfix31_En27
  SIGNAL Add1_sub_cast                    : signed(35 DOWNTO 0);  -- sfix36_En28
  SIGNAL Add1_sub_cast_1                  : signed(35 DOWNTO 0);  -- sfix36_En28
  SIGNAL Add1_sub_temp                    : signed(35 DOWNTO 0);  -- sfix36_En28
  SIGNAL Add1_out1                        : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL Delay4_out1                      : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL Bit_Shift_out1                   : unsigned(30 DOWNTO 0);  -- ufix31_En24

BEGIN
  exp_e_unsigned <= unsigned(exp_e);

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_reg <= (OTHERS => to_unsigned(16#00#, 8));
      ELSIF enb = '1' THEN
        Delay_reg(0) <= exp_e_unsigned;
        Delay_reg(1) <= Delay_reg(0);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(1);

  Constant_out1 <= signed'("010110001011100100001011111111000");

  Product_cast <= signed(resize(Delay_out1, 9));
  Product_mul_temp <= Product_cast * Constant_out1;
  Product_out1 <= Product_mul_temp(40 DOWNTO 0);

  Product_out1_1 <= Product_out1(38 DOWNTO 4);

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1 <= to_signed(0, 35);
      ELSIF enb = '1' THEN
        Delay2_out1 <= Product_out1_1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  y_e_signed <= signed(y_e);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_reg <= (OTHERS => to_signed(16#00000000#, 31));
      ELSIF enb = '1' THEN
        Delay1_reg(0) <= y_e_signed;
        Delay1_reg(1) <= Delay1_reg(0);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(1);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1 <= to_signed(16#00000000#, 31);
      ELSIF enb = '1' THEN
        Delay3_out1 <= Delay1_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Add1_sub_cast <= resize(Delay2_out1, 36);
  Add1_sub_cast_1 <= resize(Delay3_out1 & '0', 36);
  Add1_sub_temp <= Add1_sub_cast - Add1_sub_cast_1;
  Add1_out1 <= unsigned(Add1_sub_temp(34 DOWNTO 4));

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= to_unsigned(16#00000000#, 31);
      ELSIF enb = '1' THEN
        Delay4_out1 <= Add1_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Bit_Shift_out1 <= Delay4_out1 sll 1;

  e <= std_logic_vector(Bit_Shift_out1);

END rtl;

