-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\whdlAWGNGenerator\log.vhd
-- Created: 2026-03-04 09:56:05
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: log
-- Source Path: whdlAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/logImplementation/log
-- Hierarchy Level: 3
-- Model version: 2.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY log IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u0_48_48                          :   IN    std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
        e                                 :   OUT   std_logic_vector(30 DOWNTO 0)  -- ufix31_En24
        );
END log;


ARCHITECTURE rtl OF log IS

  -- Component Declarations
  COMPONENT RangeReduction_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          x                               :   IN    std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
          x_e                             :   OUT   std_logic_vector(48 DOWNTO 0);  -- ufix49_En48
          exp_e                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT FunctionEvaluation_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          x_e                             :   IN    std_logic_vector(48 DOWNTO 0);  -- ufix49_En48
          exp_eIn                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          y_e                             :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En27
          exp_eOut                        :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT RangeReconstruction_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          y_e                             :   IN    std_logic_vector(30 DOWNTO 0);  -- sfix31_En27
          exp_e                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          e                               :   OUT   std_logic_vector(30 DOWNTO 0)  -- ufix31_En24
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RangeReduction_block
    USE ENTITY work.RangeReduction_block(rtl);

  FOR ALL : FunctionEvaluation_block
    USE ENTITY work.FunctionEvaluation_block(rtl);

  FOR ALL : RangeReconstruction_block
    USE ENTITY work.RangeReconstruction_block(rtl);

  -- Signals
  SIGNAL x_e                              : std_logic_vector(48 DOWNTO 0);  -- ufix49
  SIGNAL RangeReduction_out2              : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL FunctionEvaluation_out1          : std_logic_vector(30 DOWNTO 0);  -- ufix31
  SIGNAL FunctionEvaluation_out2          : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL y                                : std_logic_vector(30 DOWNTO 0);  -- ufix31

BEGIN
  u_RangeReduction : RangeReduction_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              x => u0_48_48,  -- ufix48_En48
              x_e => x_e,  -- ufix49_En48
              exp_e => RangeReduction_out2  -- uint8
              );

  u_FunctionEvaluation : FunctionEvaluation_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              x_e => x_e,  -- ufix49_En48
              exp_eIn => RangeReduction_out2,  -- uint8
              y_e => FunctionEvaluation_out1,  -- sfix31_En27
              exp_eOut => FunctionEvaluation_out2  -- uint8
              );

  u_RangeReconstruction : RangeReconstruction_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              y_e => FunctionEvaluation_out1,  -- sfix31_En27
              exp_e => FunctionEvaluation_out2,  -- uint8
              e => y  -- ufix31_En24
              );

  e <= y;

END rtl;

