-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\whdlAWGNGenerator\SinCos.vhd
-- Created: 2026-03-04 09:56:05
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SinCos
-- Source Path: whdlAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/SinCos
-- Hierarchy Level: 2
-- Model version: 2.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SinCos IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u1                                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        g0                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        g1_16_15                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END SinCos;


ARCHITECTURE rtl OF SinCos IS

  -- Component Declarations
  COMPONENT Sine_HDL_Optimized
    PORT( u                               :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          x                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  COMPONENT Sine_HDL_Optimized1
    PORT( u                               :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          x                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Sine_HDL_Optimized
    USE ENTITY work.Sine_HDL_Optimized(rtl);

  FOR ALL : Sine_HDL_Optimized1
    USE ENTITY work.Sine_HDL_Optimized1(rtl);

  -- Signals
  SIGNAL u1_unsigned                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Delay2_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL g0_1                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL g0_signed                        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay_out1                       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL g1_16_15_1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Cosine                           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Cosine_signed                    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  u_Sine_HDL_Optimized : Sine_HDL_Optimized
    PORT MAP( u => std_logic_vector(Delay2_out1),  -- ufix16_En16
              x => g0_1  -- sfix16_En15
              );

  u_Sine_HDL_Optimized1 : Sine_HDL_Optimized1
    PORT MAP( u => std_logic_vector(g1_16_15_1),  -- ufix16_En16
              x => Cosine  -- sfix16_En15
              );

  u1_unsigned <= unsigned(u1);

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1 <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        Delay2_out1 <= u1_unsigned;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  g0_signed <= signed(g0_1);

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_out1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        Delay_out1 <= g0_signed;
      END IF;
    END IF;
  END PROCESS Delay_process;


  g0 <= std_logic_vector(Delay_out1);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        g1_16_15_1 <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        g1_16_15_1 <= u1_unsigned;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Cosine_signed <= signed(Cosine);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        Delay1_out1 <= Cosine_signed;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  g1_16_15 <= std_logic_vector(Delay1_out1);

END rtl;

