# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/qianzha/Desktop/Embedded-System-Project-DAT096/Board_1/Board_1/Board_2.srcs/sources_1/bd/design_2/ip/design_2_ZmodAWGController_0_0/design_2_ZmodAWGController_0_0.xci
# IP: The module: 'design_2_ZmodAWGController_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qianzha/Desktop/Embedded-System-Project-DAT096/Board_1/Board_1/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodAWGController_0_0/ConstrsZmodDAC.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ZmodAWGController_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/qianzha/Desktop/Embedded-System-Project-DAT096/Board_1/Board_1/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodAWGController_0_0/constr/ConstrZmodDAC1411_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ZmodAWGController_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/qianzha/Desktop/Embedded-System-Project-DAT096/Board_1/Board_1/Board_2.srcs/sources_1/bd/design_2/ip/design_2_ZmodAWGController_0_0/design_2_ZmodAWGController_0_0.xci
# IP: The module: 'design_2_ZmodAWGController_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qianzha/Desktop/Embedded-System-Project-DAT096/Board_1/Board_1/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodAWGController_0_0/ConstrsZmodDAC.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ZmodAWGController_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/qianzha/Desktop/Embedded-System-Project-DAT096/Board_1/Board_1/Board_2.gen/sources_1/bd/design_2/ip/design_2_ZmodAWGController_0_0/constr/ConstrZmodDAC1411_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ZmodAWGController_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
