# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.srcs/sources_1/bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0.xci
# IP: The module: 'vcsel_block_design_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.gen/sources_1/bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcsel_block_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.gen/sources_1/bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcsel_block_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.gen/sources_1/bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcsel_block_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.srcs/sources_1/bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0.xci
# IP: The module: 'vcsel_block_design_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.gen/sources_1/bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcsel_block_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.gen/sources_1/bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcsel_block_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/arikb/Desktop/VCSEL_implementation/VCSEL_implementation.gen/sources_1/bd/vcsel_block_design/ip/vcsel_block_design_clk_wiz_0_0/vcsel_block_design_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcsel_block_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
